# Generated by Django 4.2.2 on 2023-06-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта пользователя')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('scheduled_at', models.DateTimeField(verbose_name='Время планирования')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_service_app.mailing', verbose_name='Рассылка')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_service_app.client', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail_service_app.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылок',
            },
        ),
    ]
