# Generated by Django 4.2.2 on 2023-07-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service_app', '0002_alter_mailinglog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='title',
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default=' ', max_length=150, verbose_name='Тема письма'),
        ),
    ]
