# Generated by Django 4.2.2 on 2023-07-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service_app', '0003_remove_mailing_title_alter_message_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='content',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('Ежедневно', 'Ежедневно'), ('Еженедельно', 'Еженедельно'), ('Ежемесячно', 'Ежемесячно')], default='Ежедневно', max_length=50, verbose_name='Периодичность'),
        ),
    ]
