# Generated by Django 4.2.2 on 2023-07-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service_app', '0004_rename_content_mailing_title_alter_mailing_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=50, verbose_name='Статус рассылки'),
        ),
    ]
