# Generated by Django 4.2.2 on 2023-07-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service_app', '0005_mailing_mailing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='scheduled_at',
        ),
    ]
